name: Chromatic (main)
on: push
jobs:
  chromatic:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    continue-on-error: true
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.12.0
          cache: 'yarn'
      - name: Install and Build 🔧
        run: yarn
      - name: Publish to Chromatic and auto accept changes
        if: github.ref == 'refs/heads/main'
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true
