name: Chromatic
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.12.0
          cache: 'yarn'
      - name: Install and Build 🔧
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        id: chromatic
        # Chromatic GitHub Action options
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: 'main'
          exitZeroOnChanges: true
          exitOnceUploaded: true
      - name: comment PR
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Chromatic Storybook: [${{ steps.chromatic.outputs.storybookUrl }}](${{ steps.chromatic.outputs.storybookUrl }})"
          check_for_duplicate_msg: true
