# This is a basic workflow to help you get started with Actions

name: Project Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on issue open events but only for the main branch
  issues:
    types:
      - opened

jobs:
  issue-tagging-job-analytics-standard:
    runs-on: ubuntu-latest
    name: Assign sub-issues with parents label and project
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Shopify/analytical-standards-github-actions
          ref: v1.7
          token: ${{ secrets.AS_ACTION_PAT }} # stored in GitHub secrets
          path: .github/actions/analytical-standards-github-actions
      - name: 'Label issue if parent contains "VizX" label'
        id: issue_labelling
        uses: ./.github/actions/analytical-standards-github-actions/issue-labelling
        with:
          project-label: "VizX"
          issue-id: ${{ github.event.issue.number }}
          repo-name: ${{ github.event.repository.name }}
          repo-owner: ${{ github.event.repository.owner.login }}
          stories-label: "Story"
        env:
          GRAPHQL_API_BASE: "https://api.github.com"
          PAT_TOKEN: ${{ secrets.AS_ACTION_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the action result
        run: echo "AutoLabel Job success ${{ steps.issue_labelling.outputs.success }}"
      - name: 'Move issue to "VizX" project'
        id: project_next_move
        uses: ./.github/actions/analytical-standards-github-actions/issue-to-project
        with:
          project-label: "Analytical Standards"
          project-next-number: 3602
          organization: "Shopify"
          issue-id: ${{ github.event.issue.number }}
          repo-name: ${{ github.event.repository.name }}
          repo-owner: ${{ github.event.repository.owner.login }}
          stories-label: "Story"
        env:
          GRAPHQL_API_BASE: "https://api.github.com"
          PAT_TOKEN: ${{ secrets.AS_ACTION_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the project move step
      - name: Get the move result
        run: |
          echo "Project move job success ${{ steps.project_next_move.outputs.success }}"
          echo "The parent milestone was ${{ steps.issue_labelling.outputs.milestoneTitle }}"
          echo "The project item Id was ${{ steps.project_next_move.outputs.itemId }}"
      - name: issue templating step
        id: issue_templating
        uses: ./.github/actions/analytical-standards-github-actions/issue-templating
        with:
          project-label: "Analytical Standards"
          stories-label: "Story"
          base-path: './.github/actions/analytical-standards-github-actions/issue-templating'
          project-next-number: 1908
          issue-id: ${{ github.event.issue.number }}
          repo-name: ${{ github.event.repository.name }}
          repo-owner: ${{ github.event.repository.owner.login }}
          organization: "Shopify"
        env:
          GRAPHQL_API_BASE: 'https://api.github.com'
          PAT_TOKEN: ${{ secrets.KENNY_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
